src/avatar/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('avatar.views',
    url('^add/$', 'add', name='avatar_add'),
    url('^change/$', 'change', name='avatar_change'),
    url('^delete/$', 'delete', name='avatar_delete'),
    url('^render_primary/(?P<user>[\+\w]+)/(?P<size>[\d]+)/$', 'render_primary', name='avatar_render_primary'),    
)

src/forum/urls.py
"""
URLConf for Django-Forum.

django-forum assumes that the forum application is living under
/forum/.

Usage in your base urls.py:
    (r'^forum/', include('forum.urls')),

"""

from django.conf.urls.defaults import *
from forum.models import Forum
from forum.feeds import RssForumFeed, AtomForumFeed
from forum.sitemap import ForumSitemap, ThreadSitemap, PostSitemap

feed_dict = {
    'rss' : RssForumFeed,
    'atom': AtomForumFeed
}

sitemap_dict = {
    'forums': ForumSitemap,
    'threads': ThreadSitemap,
    'posts': PostSitemap,
}

urlpatterns = patterns('',
    url(r'^$', 'forum.views.forums_list', name='forum_index'),

    # url(r'^(?P<url>(rss|atom).*)/$', 'django.contrib.syndication.views.Feed', {'feed_dict': feed_dict}),

    url(r'^thread/(?P<thread>[0-9]+)/$', 'forum.views.thread', name='forum_view_thread'),
    # url(r'^thread/(?P<thread>[0-9]+)/reply/$', 'forum.views.reply', name='forum_reply_thread'),

    url(r'^subscriptions/$', 'forum.views.updatesubs', name='forum_subscriptions'),

    url(r'^(?P<slug>[-\w]+)/$', 'forum.views.forum', name='forum_thread_list'),
    # url(r'^(?P<forum>[-\w]+)/new/$', 'forum.views.newthread', name='forum_new_thread'),

    # url(r'^([-\w/]+/)(?P<forum>[-\w]+)/new/$', 'forum.views.newthread'),
    url(r'^([-\w/]+/)(?P<slug>[-\w]+)/$', 'forum.views.forum', name='forum_subforum_thread_list'),

    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.index', {'sitemaps': sitemap_dict}),
    (r'^sitemap-(?P<section>.+)\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemap_dict}),
)

src/userena/urls.py
from django.conf.urls.defaults import *
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from userena import views as userena_views
from userena import settings as userena_settings

urlpatterns = patterns('',
    # Signup, signin and signout
    url(r'^signup/$',
       userena_views.signup,
       name='userena_signup'),
    url(r'^signin/$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^signout/$',
       userena_views.signout,
       name='userena_signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       {'template_name': 'userena/password_reset_form.html',
        'email_template_name': 'userena/emails/password_reset_message.txt'},
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'userena/password_reset_done.html'},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
       auth_views.password_reset_confirm,
       {'template_name': 'userena/password_reset_confirm_form.html'},
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'userena/password_reset_complete.html'}),

    # Signup
    url(r'^(?P<username>[\.\w]+)/signup/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/signup_complete.html',
        'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
                          'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
       name='userena_signup_complete'),

    # Activate
    url(r'^activate/(?P<activation_key>\w+)/$',
       userena_views.activate,
       name='userena_activate'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w]+)/email/$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w]+)/email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w]+)/confirm-email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^confirm-email/(?P<confirmation_key>\w+)/$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w]+)/disabled/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w]+)/password/$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w]+)/password/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w]+)/edit/$',
       userena_views.profile_edit,
       name='userena_profile_edit'),

    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w]+)/$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^page/(?P<page>[0-9]+)/$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list'),
)

src/forum/models.py
""" 
A basic forum model with corresponding thread/post models.

Just about all logic required for smooth updates is in the save() 
methods. A little extra logic is in views.py.
"""

from django.db import models
import datetime
from django.contrib.auth.models import User, Group
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.utils.html import escape
try:
    from markdown import markdown
except ImportError:
    class MarkdownNotFound(Exception):
        def __str__(self):
            return "Markdown is not installed!"
    raise MarkdownNotFound

from forum.managers import ForumManager

class Forum(models.Model):
    """
    Very basic outline for a Forum, or group of threads. The threads
    and posts fielsd are updated by the save() methods of their
    respective models and are used for display purposes.

    All of the parent/child recursion code here is borrowed directly from
    the Satchmo project: http://www.satchmoproject.com/
    """
    groups = models.ManyToManyField(Group, blank=True)
    title = models.CharField(_("Title"), max_length=100)
    slug = models.SlugField(_("Slug"))
    parent = models.ForeignKey('self', blank=True, null=True, related_name='child')
    description = models.TextField(_("Description"))
    threads = models.IntegerField(_("Threads"), default=0, editable=False)
    posts = models.IntegerField(_("Posts"), default=0, editable=False)
    ordering = models.IntegerField(_("Ordering"), blank=True, null=True)

    objects = ForumManager()

    def _get_forum_latest_post(self):
        """This gets the latest post for the forum"""
        if not hasattr(self, '__forum_latest_post'):
            try:
                self.__forum_latest_post = Post.objects.filter(thread__forum__pk=self.id).latest("time")
            except Post.DoesNotExist:
                self.__forum_latest_post = None

        return self.__forum_latest_post
    forum_latest_post = property(_get_forum_latest_post)

    def _recurse_for_parents_slug(self, forum_obj):
        #This is used for the urls
        p_list = []
        if forum_obj.parent_id:
            p = forum_obj.parent
            p_list.append(p.slug)
            more = self._recurse_for_parents_slug(p)
            p_list.extend(more)
        if forum_obj == self and p_list:
            p_list.reverse()
        return p_list

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        p_list = self._recurse_for_parents_slug(self)
        p_list.append(self.slug)
        return '%s%s/' % (reverse('forum_index'), '/'.join (p_list))

    def _recurse_for_parents_name(self, forum_obj):
        #This is used for the visual display & save validation
        p_list = []
        if forum_obj.parent_id:
            p = forum_obj.parent
            p_list.append(p.title)
            more = self._recurse_for_parents_name(p)
            p_list.extend(more)
        if forum_obj == self and p_list:
            p_list.reverse()
        return p_list

    def get_separator(self):
        return ' &raquo; '

    def _parents_repr(self):
        p_list = self._recurse_for_parents_name(self)
        return self.get_separator().join(p_list)
    _parents_repr.short_description = _("Forum parents")

    def _recurse_for_parents_name_url(self, forum__obj):
        #Get all the absolute urls and names (for use in site navigation)
        p_list = []
        url_list = []
        if forum__obj.parent_id:
            p = forum__obj.parent
            p_list.append(p.title)
            url_list.append(p.get_absolute_url())
            more, url = self._recurse_for_parents_name_url(p)
            p_list.extend(more)
            url_list.extend(url)
        if forum__obj == self and p_list:
            p_list.reverse()
            url_list.reverse()
        return p_list, url_list

    def get_url_name(self):
        #Get a list of the url to display and the actual urls
        p_list, url_list = self._recurse_for_parents_name_url(self)
        p_list.append(self.title)
        url_list.append(self.get_absolute_url())
        return zip(p_list, url_list)

    def __unicode__(self):
        return u'%s' % self.title
    
    class Meta:
        ordering = ['ordering', 'title',]
        verbose_name = _('Forum')
        verbose_name_plural = _('Forums')

    def save(self, force_insert=False, force_update=False):
        p_list = self._recurse_for_parents_name(self)
        if (self.title) in p_list:
            raise validators.ValidationError(_("You must not save a forum in itself!"))
        super(Forum, self).save(force_insert, force_update)

    def _flatten(self, L):
        """
        Taken from a python newsgroup post
        """
        if type(L) != type([]): return [L]
        if L == []: return L
        return self._flatten(L[0]) + self._flatten(L[1:])

    def _recurse_for_children(self, node):
        children = []
        children.append(node)
        for child in node.child.all():
            children_list = self._recurse_for_children(child)
            children.append(children_list)
        return children

    def get_all_children(self):
        """
        Gets a list of all of the children forums.
        """
        children_list = self._recurse_for_children(self)
        flat_list = self._flatten(children_list[1:])
        return flat_list

class Thread(models.Model):
    """
    A Thread belongs in a Forum, and is a collection of posts.

    Threads can be closed or stickied which alter their behaviour 
    in the thread listings. Again, the posts & views fields are 
    automatically updated with saving a post or viewing the thread.
    """
    forum = models.ForeignKey(Forum)
    title = models.CharField(_("Title"), max_length=100)
    sticky = models.BooleanField(_("Sticky?"), blank=True, default=False)
    closed = models.BooleanField(_("Closed?"), blank=True, default=False)
    posts = models.IntegerField(_("Posts"), default=0)
    views = models.IntegerField(_("Views"), default=0)
    latest_post_time = models.DateTimeField(_("Latest Post Time"), blank=True, null=True)

    def _get_thread_latest_post(self):
        """This gets the latest post for the thread"""
        if not hasattr(self, '__thread_latest_post'):
            try:
                self.__thread_latest_post = Post.objects.filter(thread__pk=self.id).latest("time")
            except Post.DoesNotExist:
                self.__thread_latest_post = None

        return self.__thread_latest_post
    thread_latest_post = property(_get_thread_latest_post)

    class Meta:
        ordering = ('-sticky', '-latest_post_time')
        verbose_name = _('Thread')
        verbose_name_plural = _('Threads')

    def save(self, force_insert=False, force_update=False):
        f = self.forum
        f.threads = f.thread_set.count()
        f.save()
        if not self.sticky:
            self.sticky = False
        super(Thread, self).save(force_insert, force_update)

    def delete(self):
        super(Thread, self).delete()
        f = self.forum
        f.threads = f.thread_set.count()
        f.posts = Post.objects.filter(thread__forum__pk=f.id).count()
        f.save()
    
    def get_absolute_url(self):
        return ('forum_view_thread', [str(self.id)])
    get_absolute_url = models.permalink(get_absolute_url)
    
    def __unicode__(self):
        return u'%s' % self.title

class Post(models.Model):
    """ 
    A Post is a User's input to a thread. Uber-basic - the save() 
    method also updates models further up the heirarchy (Thread,Forum)
    """
    thread = models.ForeignKey(Thread)
    author = models.ForeignKey(User, related_name='forum_post_set')
    body = models.TextField(_("Body"))
    body_html = models.TextField(editable=False)
    time = models.DateTimeField(_("Time"), blank=True, null=True)

    def save(self, force_insert=False, force_update=False):
        if not self.id:
            self.time = datetime.datetime.now()
        
        self.body_html = markdown(escape(self.body))
        super(Post, self).save(force_insert, force_update)

        t = self.thread
        t.latest_post_time = t.post_set.latest('time').time
        t.posts = t.post_set.count()
        t.save()

        f = self.thread.forum
        f.threads = f.thread_set.count()
        f.posts = Post.objects.filter(thread__forum__pk=f.id).count()
        f.save()

    def delete(self):
        try:
            latest_post = Post.objects.exclude(pk=self.id).latest('time')
            latest_post_time = latest_post.time
        except Post.DoesNotExist:
            latest_post_time = None

        t = self.thread
        t.posts = t.post_set.exclude(pk=self.id).count()
        t.latest_post_time = latest_post_time
        t.save()

        f = self.thread.forum
        f.posts = Post.objects.filter(thread__forum__pk=f.id).exclude(pk=self.id).count()
        f.save()

        super(Post, self).delete()

    class Meta:
        ordering = ('-time',)
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')
        
    def get_absolute_url(self):
        return '%s?page=last#post%s' % (self.thread.get_absolute_url(), self.id)
    
    def __unicode__(self):
        return u"%s" % self.id

class Subscription(models.Model):
    """
    Allow users to subscribe to threads.
    """
    author = models.ForeignKey(User)
    thread = models.ForeignKey(Thread)

    class Meta:
        unique_together = (("author", "thread"),)
        verbose_name = _('Subscription')
        verbose_name_plural = _('Subscriptions')

    def __unicode__(self):
        return u"%s to %s" % (self.author, self.thread)

src/forum/forms.py
from django import forms
from django.utils.translation import ugettext as _


class CreateThreadForm(forms.Form):
    title = forms.CharField(label=_("Title"), max_length=100)
    body = forms.CharField(label=_("Body"),
                           widget=forms.Textarea(attrs={'rows': 8, 'cols': 50, 'style': 'width: 100%;'}))
    subscribe = forms.BooleanField(label=_("Subscribe via email"), required=False)


class ReplyForm(forms.Form):
    body = forms.CharField(label=_("Body"),
                           widget=forms.Textarea(attrs={'rows': 8, 'cols': 50, 'style': 'width: 100%;'}))
    subscribe = forms.BooleanField(label=_("Subscribe via email"), required=False)

src/forum/templates/forum/forum_list.html
{% extends "forum_base.html" %}{% load i18n %}

{% block title %}{% trans "Forums" %}{% endblock %}

{% block content %}
    <table class="table table-bordered table-hover">
        <tr>
            <th>{% trans "Forum" %}</th>
            <th>{% trans "Last Post" %}</th>
        </tr>

        {% for forum in object_list %}
            <tr>
                <td class='djangoForumListDetails'><p><strong><a
                        href='{{ forum.get_absolute_url }}'>{{ forum.title }}</a></strong><br/><span
                        class='djangoForumStats'>{% blocktrans with forum.threads as thread_count and forum.posts as post_count %}
                    {{ thread_count }} тем(ы), {{ post_count }} сообщений{% endblocktrans %}</span></p>

                    <p>{{ forum.description }}</p></td>
                {% with forum.forum_latest_post as latest_post %}
                    <td>{% if latest_post %}
                        {% blocktrans with latest_post.time|timesince as time and latest_post.author as author %}
                            {{ time }} назад от пользователя {{ author }}{% endblocktrans %} (
                        <a href='{{ latest_post.get_absolute_url }}'>{% trans "view" %}</a>){% else %}
                        {% trans "No Posts" %}{% endif %}</td>
                {% endwith %}
            </tr>
        {% endfor %}
    </table>
    {% if request.user.is_authenticated %}<p>
        <a href="{% url forum_subscriptions %}">{% trans "Update Subscriptions" %}</a></p>{% endif %}
{% endblock %}

src/forum/templates/forum/newthread.html
{% extends "forum_base.html" %}
{% load i18n %}

{% block title %}{% blocktrans with forum.title as title %}New Thread in {{ title }}{% endblocktrans %}{% endblock %}

{% block extrahead %}
<link rel="alternate" type="application/rss+xml" title="{% blocktrans %}{{ forum.title }} Posts via RSS{% endblocktrans %}" href="{% url forum_index %}rss/{{ forum.slug }}/" />
<link rel="alternate" type="application/atom+xml" title="{% blocktrans %}{{ forum.title }} Posts via ATOM{% endblocktrans %}" href="{% url forum_index %}atom/{{ forum.slug }}/" />
{% endblock %}

{% block pagetitle %}{% blocktrans with forum.title as title %}New Thread in {{ title }}{% endblocktrans %}{% endblock %}

{% block breadcrumbs %} {% for title, url in forum.get_url_name %} &raquo; <a href='{{ url }}'>{{ title }}</a> {% endfor %} &raquo; {% trans "New Thread" %}{% endblock %}


{% block content %}

<h2>{% trans "Create a Thread" %}</h2>
<form method='post' action='./'>
{% csrf_token %}
{% if form.errors %}<ul>{{ form.errors.as_ul }}</ul>{% endif %}
<p><label>{% trans "Posting As" %}</label><span>{{ user.username }}</span></p>
{{ form.as_p }}
<p><input type='submit' value='{% trans "Post" %}' /></p>
</form>

{% endblock %}

src/forum/templates/forum/reply.html
{% extends "forum_base.html" %}
{% load i18n %}

{% block title %}{% blocktrans with thread.title as title %}Reply to thread  "{{ title }}"{% endblocktrans %}{% endblock %}

{% block pagetitle %}{% blocktrans with thread.title as title %}Reply to Thread "{{ title }}"{% endblocktrans %}{% endblock %}

{% block breadcrumbs %}{% for title, url in thread.forum.get_url_name %} &raquo; <a href='{{ url }}'>{{ title }}</a>{% endfor %} &raquo; <a href='{{ thread.get_absolute_url }}'>{{ thread.title|escape }}</a> &raquo; Reply{% endblock %}


{% block content %}

<h2>{% trans "Reply to Thread" %}</h2>
<form method='post' action='./'>
{% if form.errors %}<ul>{{ form.errors.as_ul }}</ul>{% endif %}
<p><label>{% trans "Posting As" %}</label><span>{{ user.username }}</span></p>
{{ form.as_p }}
<p><input type='submit' value='{% trans "Post" %}' /></p>
</form>

{% endblock %}

src/forum/templates/forum/thread.html
{% extends "forum_base.html" %}
{% load i18n %}
{% load odnosidelci_avatar_tags %}
{% block title %}{{ thread.title|escape }} ({{ forum.title }}){% endblock %}

{% block pagetitle %}{{ forum.title }} &raquo; {{ thread.title|escape }}{% endblock %}


{% block breadcrumbs %}
    {% for title, url in thread.forum.get_url_name %}
        <li><span class="divider">/</span></li>
        <li><a href='{{ url }}'>{{ title }}</a></li>
    {% endfor %}
    <li><span class="divider">/</span></li>
    <li><a href='{{ thread.get_absolute_url }}'>{{ thread.title|escape }}</a></li>
    ({{ thread.posts }}
    {% blocktrans count thread.posts as counter %}post{% plural %}posts{% endblocktrans %}){% endblock %}

{% block content %}

    <table class="table table-striped table-bordered" id=''>
        {% for post in post_list %}

            <tr>
                <td id='post{{ post.id }}' style="width: 20%;">
                    {% odnosidelci_avatar post.author %}
                    <p>{% trans "by" %} <strong>{{ post.author }}</strong></p>

                    <p>{% blocktrans with post.time|timesince as time %}{{ time }} назад{% endblocktrans %}<br/></p>

                <td>{{ post.body_html|safe }}</td>
            </tr>{% endfor %}

    </table>



    {% if is_paginated %}
        <div class="pagination pagination-centered pagination-large">
            <ul>
                {% if page == 1 %}
                    <li class="disabled"><a href="?page=1">&laquo;</a></li>
                {% else %}
                    <li><a href="?page=1">&laquo;</a></li>
                {% endif %}

                {% for page_number in paginator.page_range %}
                    {% if page == page_number %}
                        <li class="active"><a href="?page={{ page_number }}">{{ page_number }}</a></li>
                    {% else %}
                        <li><a href="?page={{ page_number }}">{{ page_number }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page == paginator.num_pages %}
                    <li class="disabled"><a href="?page={{ paginator.num_pages }}">&raquo;</a></li>
                {% else %}
                    <li><a href="?page={{ paginator.num_pages }}">&raquo;</a></li>
                {% endif %}
            </ul>
        </div>
    {% endif %}

    {% if request.user.is_authenticated %}<p>
        <a href="{% url forum_subscriptions %}?next={{ request.path }}">{% trans "Update Subscriptions" %}</a></p>
    {% endif %}
    {% if thread.closed %}
        <p>{% trans "Sorry, this thread is closed. No further replies are permitted." %}</p>
    {% else %}
    <!--
        {% if user.is_authenticated %}
            <div class="panel panel-default">
                <div class="panel-heading" style="padding: 1px 15px;">
                    <h5>Написать сообщение, пользователь <span>{{ user.username }}</span></h5>
                </div>
                <div class="panel-body">
                    <form method='post' action='reply/'>
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input class="btn btn-primary" type='submit' value='{% trans "Submit" %}'/>
                    </form>
                </div>
            </div>
        {% else %}
            <p class="alert alert-success">Только зарегистрированные пользователи могут оставлять комментарии.
                <a href="/accounts/signin/" rel="nofollow">Войдите</a>, пожалуйста.</p>
        {% endif %}
      -->
    {% endif %}

{% endblock %}

src/forum/templates/forum/thread_list.html
{% extends "forum_base.html" %}
{% load i18n %}

{% block title %}{{ forum.title }}{% endblock %}

{% block extrahead %}
    <link rel="alternate" type="application/rss+xml"
          title="{% blocktrans with forum.title as ftitle %}{{ ftitle }} Posts via RSS{% endblocktrans %}"
          href="{% url forum_index %}rss/{{ forum.slug }}/"/>
    <link rel="alternate" type="application/atom+xml"
          title="{% blocktrans with forum.title as ftitle %}{{ ftitle }} Posts via ATOM{% endblocktrans %}"
          href="{% url forum_index %}atom/{{ forum.slug }}/"/>
{% endblock %}

{% block pagetitle %}{{ forum.title }}{% endblock %}

{% block breadcrumbs %}
    {% for title, url in forum.get_url_name %}
        <li><span class="divider">/</span></li>
        <li><a href='{{ url }}'>{{ title }}</a></li>
    {% endfor %} ({{ forum.threads }} тем(ы),  {{ forum.posts }}
    сообщений)
{% endblock %}


{% block content %}

    {% if child_forums %}
        <table class="table table-striped table-bordered">
            <tr>
                <th>{# {% trans "Sub-Forum" %} #}Подфорум</th>
                <th>{% trans "Last Post" %}</th>
            </tr>

            {% for subforum in child_forums %}
                <tr>
                    <td class='djangoForumListDetails'><p><strong><a
                            href='{{ subforum.get_absolute_url }}'>{{ subforum.title }}</a></strong><br/><span
                            class='djangoForumStats'>{{ subforum.threads }} {# {% trans "thread" %}{{ subforum.threads|pluralize }} #} тем(ы), {{ subforum.posts }}
                        сообщений {# {% trans "post" %}{{ subforum.posts|pluralize }} #}</span></p>

                        <p>{{ subforum.description }}</p></td>
                    {% with subforum.forum_latest_post as latest_post %}
                        <td class=''>{% if latest_post %}
                            {% blocktrans with post.time|timesince as time and latest_post.author as author %}{{ time }}
                                назад от пользователя {{ author }}{% endblocktrans %} (
                            <a href='{{ latest_post.get_absolute_url }}'>{% trans "view" %}</a>){% else %}
                            {% trans "No Posts" %}{% endif %}</td>
                    {% endwith %}
                </tr>
            {% endfor %}
        </table>
        <br/>
    {% endif %}

    <table class="table table-striped table-bordered">

        <tr>
            <th>{% trans "Thread" %}</th>
            <th style='width: 50px;'>{% trans "Posts" %}</th>
            <th style='width: 50px;'>{% trans "Views" %}</th>
            <th style='width: 220px;'>{% trans "Last Post" %}</th>
        </tr>

        {% for t in thread_list %}
            <tr>
                <td>{% if t.sticky %}Sticky {% endif %}<a href='{{ t.get_absolute_url }}'>{{ t.title|escape }}</a>
                    {% if t.closed %} (Closed){% endif %}</td>
                <td style='width: 50px;'>{{ t.posts }}</td>
                <td style='width: 50px;'>{{ t.views }}</td>
                {% with t.thread_latest_post as latest_post %}
                    <td style='width: 220px;' class=''>
                        {% blocktrans with latest_post.time|timesince as time and latest_post.author as author %}
                            {{ time }} назад от пользователя {{ author }}{% endblocktrans %} (<a
                            href='{{ latest_post.get_absolute_url }}'>{% trans "view" %}</a>)
                    </td>
                {% endwith %}
            </tr>
        {% endfor %}
    </table>


    {% if is_paginated %}
        <div class="pagination pagination-centered pagination-large">
            <ul>
                {% if page == 1 %}
                    <li class="disabled"><a href="?page=1">&laquo;</a></li>
                {% else %}
                    <li><a href="?page=1">&laquo;</a></li>
                {% endif %}

                {% for page_number in paginator.page_range %}
                    {% if page == page_number %}
                        <li class="active"><a href="?page={{ page_number }}">{{ page_number }}</a></li>
                    {% else %}
                        <li><a href="?page={{ page_number }}">{{ page_number }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page == paginator.num_pages %}
                    <li class="disabled"><a href="?page={{ paginator.num_pages }}">&raquo;</a></li>
                {% else %}
                    <li><a href="?page={{ paginator.num_pages }}">&raquo;</a></li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
<!--
    {% if user.is_authenticated %}
        <div class="panel panel-default">
            <div class="panel-heading" style="padding: 1px 15px;">
                <h5>Создать тему, пользователь <span>{{ user.username }}</span></h5>
            </div>
            <div class="panel-body">
                <form method='post' action='new/'>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p><input class="btn btn-primary" type='submit' value='Создать'/></p>
                </form>
            </div>
        </div>

    {% else %}
        <p class="alert alert-success">Только зарегистрированные пользователи могут создавать темы.
<a href="/accounts/signin/" rel="nofollow">Войдите</a>, пожалуйста.</p>
    {% endif %}
-->

{% endblock %}