src/avatar/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('avatar.views',
    url('^add/$', 'add', name='avatar_add'),
    url('^change/$', 'change', name='avatar_change'),
    url('^delete/$', 'delete', name='avatar_delete'),
    url('^render_primary/(?P<user>[\+\w]+)/(?P<size>[\d]+)/$', 'render_primary', name='avatar_render_primary'),    
)

src/forum/urls.py
"""
URLConf for Django-Forum.

django-forum assumes that the forum application is living under
/forum/.

Usage in your base urls.py:
    (r'^forum/', include('forum.urls')),

"""

from django.conf.urls.defaults import *
from forum.models import Forum
from forum.feeds import RssForumFeed, AtomForumFeed
from forum.sitemap import ForumSitemap, ThreadSitemap, PostSitemap

feed_dict = {
    'rss' : RssForumFeed,
    'atom': AtomForumFeed
}

sitemap_dict = {
    'forums': ForumSitemap,
    'threads': ThreadSitemap,
    'posts': PostSitemap,
}

urlpatterns = patterns('',
    url(r'^$', 'forum.views.forums_list', name='forum_index'),

    # url(r'^(?P<url>(rss|atom).*)/$', 'django.contrib.syndication.views.Feed', {'feed_dict': feed_dict}),

    url(r'^thread/(?P<thread>[0-9]+)/$', 'forum.views.thread', name='forum_view_thread'),
    # url(r'^thread/(?P<thread>[0-9]+)/reply/$', 'forum.views.reply', name='forum_reply_thread'),

    url(r'^subscriptions/$', 'forum.views.updatesubs', name='forum_subscriptions'),

    url(r'^(?P<slug>[-\w]+)/$', 'forum.views.forum', name='forum_thread_list'),
    # url(r'^(?P<forum>[-\w]+)/new/$', 'forum.views.newthread', name='forum_new_thread'),

    # url(r'^([-\w/]+/)(?P<forum>[-\w]+)/new/$', 'forum.views.newthread'),
    url(r'^([-\w/]+/)(?P<slug>[-\w]+)/$', 'forum.views.forum', name='forum_subforum_thread_list'),

    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.index', {'sitemaps': sitemap_dict}),
    (r'^sitemap-(?P<section>.+)\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemap_dict}),
)

src/userena/contrib/umessages/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to

from userena.contrib.umessages import views as messages_views

urlpatterns = patterns('',
    url(r'^compose/$',
        messages_views.message_compose,
        name='userena_umessages_compose'),

    url(r'^compose/(?P<recipients>[\+\.\w]+)/$',
        messages_views.message_compose,
        name='userena_umessages_compose_to'),

    url(r'^reply/(?P<parent_id>[\d]+)/$',
        messages_views.message_compose,
        name='userena_umessages_reply'),

    url(r'^view/(?P<username>[\.\w]+)/$',
        messages_views.message_detail,
        name='userena_umessages_detail'),

    url(r'^remove/$',
        messages_views.message_remove,
        name='userena_umessages_remove'),

    url(r'^unremove/$',
        messages_views.message_remove,
        {'undo': True},
        name='userena_umessages_unremove'),

    url(r'^$',
        messages_views.message_list,
        name='userena_umessages_list'),
)

src/userena/urls.py
from django.conf.urls.defaults import *
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from userena import views as userena_views
from userena import settings as userena_settings

urlpatterns = patterns('',
    # Signup, signin and signout
    url(r'^signup/$',
       userena_views.signup,
       name='userena_signup'),
    url(r'^signin/$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^signout/$',
       userena_views.signout,
       name='userena_signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       {'template_name': 'userena/password_reset_form.html',
        'email_template_name': 'userena/emails/password_reset_message.txt'},
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'userena/password_reset_done.html'},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
       auth_views.password_reset_confirm,
       {'template_name': 'userena/password_reset_confirm_form.html'},
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'userena/password_reset_complete.html'}),

    # Signup
    url(r'^(?P<username>[\.\w]+)/signup/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/signup_complete.html',
        'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
                          'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
       name='userena_signup_complete'),

    # Activate
    url(r'^activate/(?P<activation_key>\w+)/$',
       userena_views.activate,
       name='userena_activate'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w]+)/email/$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w]+)/email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w]+)/confirm-email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^confirm-email/(?P<confirmation_key>\w+)/$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w]+)/disabled/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w]+)/password/$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w]+)/password/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w]+)/edit/$',
       userena_views.profile_edit,
       name='userena_profile_edit'),

    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w]+)/$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^page/(?P<page>[0-9]+)/$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list'),
)

src/avatar/models.py
# -*- coding: utf-8 -*-

import datetime
import os

from django.db import models
from django.core.files.base import ContentFile
from django.utils.translation import ugettext as _
from django.utils.hashcompat import md5_constructor
from django.utils.encoding import smart_str
from django.db.models import signals

from django.contrib.auth.models import User

try:
    from cStringIO import StringIO
    dir(StringIO) # Placate PyFlakes
except ImportError:
    from StringIO import StringIO

try:
    from PIL import Image
    dir(Image) # Placate PyFlakes
except ImportError:
    import Image

from avatar.util import invalidate_cache
from avatar.settings import (AVATAR_STORAGE_DIR, AVATAR_RESIZE_METHOD,
                             AVATAR_MAX_AVATARS_PER_USER, AVATAR_THUMB_FORMAT,
                             AVATAR_HASH_USERDIRNAMES, AVATAR_HASH_FILENAMES,
                             AVATAR_THUMB_QUALITY, AUTO_GENERATE_AVATAR_SIZES)


def avatar_file_path(instance=None, filename=None, size=None, ext=None):
    tmppath = [AVATAR_STORAGE_DIR]
    if AVATAR_HASH_USERDIRNAMES:
        tmp = md5_constructor(instance.user.username).hexdigest()
        tmppath.extend([tmp[0], tmp[1], instance.user.username])
    else:
        tmppath.append(instance.user.username)
    if not filename:
        # Filename already stored in database
        filename = instance.avatar.name
        if ext and AVATAR_HASH_FILENAMES:
            # An extension was provided, probably because the thumbnail
            # is in a different format than the file. Use it. Because it's
            # only enabled if AVATAR_HASH_FILENAMES is true, we can trust
            # it won't conflict with another filename
            (root, oldext) = os.path.splitext(filename)
            filename = root + "." + ext
    else:
        # File doesn't exist yet
        if AVATAR_HASH_FILENAMES:
            (root, ext) = os.path.splitext(filename)
            filename = md5_constructor(smart_str(filename)).hexdigest()
            filename = filename + ext
    if size:
        tmppath.extend(['resized', str(size)])
    tmppath.append(os.path.basename(filename))
    return os.path.join(*tmppath)

def find_extension(format):
    format = format.lower()

    if format == 'jpeg':
        format = 'jpg'

    return format

class Avatar(models.Model):
    user = models.ForeignKey(User)
    primary = models.BooleanField(default=False)
    avatar = models.ImageField(max_length=1024, upload_to=avatar_file_path, blank=True)
    date_uploaded = models.DateTimeField(default=datetime.datetime.now)
    
    def __unicode__(self):
        return _(u'Avatar for %s') % self.user
    
    def save(self, *args, **kwargs):
        avatars = Avatar.objects.filter(user=self.user)
        if self.pk:
            avatars = avatars.exclude(pk=self.pk)
        if AVATAR_MAX_AVATARS_PER_USER > 1:
            if self.primary:
                avatars = avatars.filter(primary=True)
                avatars.update(primary=False)
        else:
            avatars.delete()
        invalidate_cache(self.user)
        super(Avatar, self).save(*args, **kwargs)
    
    def delete(self, *args, **kwargs):
        invalidate_cache(self.user)
        super(Avatar, self).delete(*args, **kwargs)
    
    def thumbnail_exists(self, size):
        return self.avatar.storage.exists(self.avatar_name(size))
    
    def create_thumbnail(self, size, quality=None):
        # invalidate the cache of the thumbnail with the given size first
        invalidate_cache(self.user, size)
        try:
            orig = self.avatar.storage.open(self.avatar.name, 'rb').read()
            image = Image.open(StringIO(orig))
        except IOError:
            return # What should we do here?  Render a "sorry, didn't work" img?
        quality = quality or AVATAR_THUMB_QUALITY
        (w, h) = image.size
        if w != size or h != size:
            if w > h:
                diff = (w - h) / 2
                image = image.crop((diff, 0, w - diff, h))
            else:
                diff = (h - w) / 2
                image = image.crop((0, diff, w, h - diff))
            if image.mode != "RGB":
                image = image.convert("RGB")
            image = image.resize((size, size), AVATAR_RESIZE_METHOD)
            thumb = StringIO()
            image.save(thumb, AVATAR_THUMB_FORMAT, quality=quality)
            thumb_file = ContentFile(thumb.getvalue())
        else:
            thumb_file = ContentFile(orig)
        thumb = self.avatar.storage.save(self.avatar_name(size), thumb_file)

    def avatar_url(self, size):
        return self.avatar.storage.url(self.avatar_name(size))
    
    def avatar_name(self, size):
        ext = find_extension(AVATAR_THUMB_FORMAT)
        return avatar_file_path(
            instance=self,
            size=size,
            ext=ext
        )


def create_default_thumbnails(instance=None, created=False, **kwargs):
    if created:
        for size in AUTO_GENERATE_AVATAR_SIZES:
            instance.create_thumbnail(size)

signals.post_save.connect(create_default_thumbnails, sender=Avatar)

src/userena/contrib/umessages/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from userena.contrib.umessages.fields import CommaSeparatedUserField
from userena.contrib.umessages.models import Message, MessageRecipient

import datetime


class ComposeForm(forms.Form):
    to = CommaSeparatedUserField(label=_("To"), widget=forms.HiddenInput)
    body = forms.CharField(label=_("Message"),
                           widget=forms.Textarea({'class': 'message', 'rows': 2, 'cols': 40, 'style': 'width: 400px;'}),
                           required=True)

    def save(self, sender):
        """
        Save the message and send it out into the wide world.

        :param sender:
            The :class:`User` that sends the message.

        :param parent_msg:
            The :class:`Message` that preceded this message in the thread.

        :return: The saved :class:`Message`.

        """
        to_user_list = self.cleaned_data['to']
        body = self.cleaned_data['body']

        msg = Message.objects.send_message(sender,
                                           to_user_list,
                                           body)

        return msg

src/userena/templates/userena/base_userena.html
{% extends "base.html" %}

src/userena/templates/userena/disabled.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Disabled account" %}{% endblock %}
{% block content_title %}<h2>{% trans "Your account has been disabled" %}</h2>{% endblock %}
{% block content %}
<p>{% trans "It seems your account has been disabled." %}</p>
<p>{% trans "If you feel that injustice has been done to you, feel free to contact the administrators to find out why" %}</p>
{% endblock %} 

src/userena/templates/userena/email_confirm_complete.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Email changed!" %}{% endblock %}

{% block content_title %}<h2>{% trans 'New email' %}</h2>{% endblock %}
{% block content %}
<p>{% blocktrans with site.name as site %}Your new email address is saved. You can continue using {{ site }} with this email.{% endblocktrans %}</p>
{% endblock %}

src/userena/templates/userena/email_confirm_fail.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Email verification failed." %}{% endblock %}
{% block content_title %}<h2>{% trans "Your email could not be verified..." %}</h2>{% endblock %}

{% block content %}
<p>{% trans "Your email could not be verified..." %}</p>
<p>{% trans "You could try changing it again in your account settings." %}</p>
{% endblock %}

src/userena/templates/userena/email_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block content_title %}<h2>{% blocktrans with user.username as username %}Account &raquo; {{ username }}{% endblocktrans %}</h2>{% endblock %}

{% block content %}
<form action="" method="post">
  <ul id="box-nav">
    <li class="first"><a href="{% url 'userena_profile_detail' user.username %}"><span>{% trans 'View profile' %}</span></a></li>
    <li><a href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit profile" %}</a></li>
    <li><a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a></li>
    <li class="last selected"><a href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a></li>
  </ul>
  {% csrf_token %}
  <fieldset>
    <legend>{% trans "Change email address" %}</legend>
    {{ form.as_p }}
  </fieldset>
  <input type="submit" value="{% trans "Change email" %}" />
</form>
{% endblock %}

src/userena/templates/userena/password_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Change password" %}{% endblock %}

{% block content_title %}<h2>{% blocktrans with user.username as username %}Account &raquo; {{ username }}{% endblocktrans %}</h2>{% endblock %}

{% block content %}
<form action="" method="post" id="password_change_form">
  <ul id="box-nav">
    <li class="first"><a href="{% url 'userena_profile_detail' user.username %}"><span>{% trans 'View profile' %}</span></a></li>
    <li><a href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit profile" %}</a></li>
    <li  class="selected"><a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a></li>
    <li class="last"><a href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a></li>
  </ul>
  <fieldset>
    <legend>{% trans "Change Password" %}</legend>
    {% csrf_token %}
    {{ form.as_p }}
  </fieldset>
  <input type="submit" value="{% trans "Change password" %}" />
</form>
{% endblock %}

src/userena/templates/userena/password_reset_complete.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Password reset" %}{% endblock %}
{% block content_title %}<h2>{% trans "Your password has been reset" %}</h2>{% endblock %}
{% block content %}
{% url 'userena_signin' as signin_url %}
{% blocktrans %}You can now <a href="{{ signin_url }}">signin</a> with your new password.{% endblocktrans %}
{% endblock %}

src/userena/templates/userena/password_reset_confirm_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Reset password" %}{% endblock %}

{% block content %}
<form action="" method="post">
  <fieldset>
    <legend>{% trans "Reset Password" %}</legend>
    {% csrf_token %}
    {{ form.as_p }}
  </fieldset>
  <input type="submit" value="{% trans "Reset password" %}" />
</form>
{% endblock %}

src/userena/templates/userena/password_reset_done.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Password reset email sent" %}{% endblock %}
{% block content_title %}<h2>{% trans "Password reset email sent" %}</h2>{% endblock %}

{% block content %}
<p>{% trans "An e-mail has been sent to you which explains how to reset your password." %}</p>
{% endblock %}

src/userena/templates/userena/profile_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Account setup" %}{% endblock %}

{% block content_title %}<h2>
    {% blocktrans with profile.user.username as username %}Account &raquo; {{ username }}{% endblocktrans %}
    </h2>{% endblock %}

{% block content %}
    <div class="content nul">
        <div class="adv v">
            <div class="ad"></div>
            <div class="ad"></div>
            <div class="ad"></div>
            <div class="ad"></div>
            <div class="ad"></div>
        </div>
        <div class="main">
            <!--<div class="profile">
            <div class="avatar">
                <img src="img/tmp/img1.jpg" alt="аватар">
            </div>
			
            <div class="info">
                <div class="name">{{u.first_name}} {{u.profile.second_name}} {{u.last_name}}</div>
                <div class="location">{{u.place}}</div>
                <div class="status">{{u.profile.mood}}</div>
                <div class="url"><a href="{{u.profile.get_absolute_url}}" title="profile url">{{u.profile.get_absolute_url}}</a></div>
                <a href="#" class="msg" title="написать сообщение"></a>
            </div>
        </div>-->
            <div class="settings profile">
                <div class="t"></div>
                <div class="c">
                    <div class="reg-form">
                        <div class="title">
                            Ваш профиль
                        </div>

                        <form action="" enctype="multipart/form-data" method="post">
                            <ul id="box-nav">
                                <li class="first"><a
                                        href="{% url 'userena_profile_detail' user.username %}"><span>{% trans 'View profile' %}</span></a>
                                </li>
                                <li class="selected"><a
                                        href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit profile" %}</a>
                                </li>
                                <li>
                                    <a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a>
                                </li>
                                <li class="last"><a
                                        href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a>
                                </li>
                            </ul>
                            {% csrf_token %}
                            <fieldset>
                                <legend>{% trans "Edit Profile" %}</legend>
                                {{ form.as_p }}
                            </fieldset>
                            <input type="submit" value="{% trans "Save changes" %}"/>
                        </form>
                    </div>
                    <div class="clr"></div>
                    <div class="title">
                        <h3>фотография профиля</h3>
                    </div>
                    <div style="overflow: hidden; margin-bottom: 15px;">
                        <div class="img">
                            {% avatar user %}
                        </div>
                        <div class="v r">
                            <!--<input type="file" name="newavatar" class="newavatar">-->
                            <a class="g" href="{% url avatar_change %}">Заменить фото профиля</a>
                        </div>
                    </div>
                    <div class="clr"></div>
                    <div class="i im">
                        {% for avatar in user.avatar_set.all %}
                            <div class="item">
                                {% render_avatar avatar 83 %}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="clr"></div>
                    <div class="v">
                        <label>Статус:</label>
                        <span>пользователь</span>
                        <a class="g" href="#" title="Купить VIP статус">Купить VIP статус</a>
                    </div>

                    </form>

                </div>

                <div class="b"></div>

            </div>

        </div>

        <div class="dashboard">

            <div class="db-arr pr"></div>

            <div class="profile mod">

                <div class="oh">

                    <div class="logo">

                        <img src="img/nd_logo.jpg" alt="">

                    </div>

                    <div class="pc-form">

                        <a class="act" href="." title="Данные профиля">Данные профиля</a>

                        <a href="/src/imprisonment/edit/" title="Редактировать ходки">Редактировать ходки</a>

                        <a href="/message/settings/" title="Настройки уведомлений">Настройки уведомлений</a>

                        <a href="/vip/" title="VIP настройки">VIP настройки</a>

                        <a href="#" title="Удалить профиль">Удалить профиль</a>

                        <a href="#" title="Справка">Справка</a>

                        <a href="/logout/" title="Выйти">Выйти</a>

                    </div>

                </div>

            </div>

            <div class="contacts mod">
                <div class="title">
                    <h3>Знакомства</h3>
                    <span>(165 новых)</span>
                    <a href="#" title="">смотреть все</a>
                </div>
                <div class="list">
                    <div class="item"></div>
                    <div class="item"></div>
                    <div class="item"></div>
                    <div class="item"></div>
                </div>
            </div>
            <div class="friends mod">
                <div class="title">
                    <h3>Друзья</h3>
                    <span>(12)</span>
                    <a href="friends.html" title="">смотреть все</a>
                </div>
                <div class="list">
                    <div class="item">
                        <div class="avatar">
                        </div>
                        <div class="name"><a href="#" title="">Сергей поляна</a></div>
                        <div class="status">Producer, Director & Designer</div>
                    </div>
                    <div class="item">
                        <div class="avatar">
                        </div>
                        <div class="name"><a href="#" title="">Валерий</a></div>
                        <div class="status">Writer, Singer & Songwriter</div>
                    </div>
                    <div class="item">
                        <div class="avatar">
                        </div>
                        <div class="name"><a href="#" title="">Черных</a><a href="#" class="msg"
                                                                            title="написать сообщение"></a></div>
                        <div class="status">Always wondering what's happening</div>
                    </div>
                </div>
            </div>
            <div class="footer mod">
                <!--
                    <a href="#" title="">About</a>
                    <a href="#" title="">Help</a>
                    <a href="#" title="">Blog</a>
                    <a href="#" title="">Mobile</a>
                    <a href="#" title="">Status</a>
                    <a href="#" title="">Jobs</a>
                    <a href="#" title="">Terms</a>
                    <a href="#" title="">Privacy</a>
                    <a href="#" title="">Shortcuts</a>
                    <a href="#" title="">Advertisers</a>
                    <a href="#" title="">Businesses</a>
                    <a href="#" title="">Media</a>
                    <a href="#" title="">Developers</a>
                    <a href="#" title="">Resources</a>
                -->
                <span class="copyright">© 2012  Odnosideltsi.com</span>

            </div>

        </div>

    </div>

    <div class="modal" style="display: none;">

        <div class="t"></div>

        <div class="clr"></div>

        <div class="c">

            <div class="add-place">

                <form action="add_place.php" method="post" name="add_place">

                    <h3>Добавить место отсидки<a href="#" class="close" title="Закрыть"></a></h3>

                    <div class="a">
                        <label>Страна</label>
                        <input type="text" name="country">
                    </div>
                    <div class="a">
                        <label>Город</label>
                        <input type="text" name="sity">
                    </div>
                    <div class="a">
                        <label>Название учреждения</label>

                        <div class="text">
                            <div class="tt"></div>
                            <div class="tc">
                                <textarea name="palce"></textarea>
                            </div>
                            <div class="tb"></div>
                        </div>
                    </div>
                    <input type="submit" class="submit" value="Добавить в список">
                </form>
            </div>
        </div>
        <div class="b"></div>
    </div>
    <div class="modal" style="display: none;">
        <div class="t"></div>
        <div class="clr"></div>
        <div class="c">
            <div class="add-friend">
                <form action="add_frien.php" method="post" name="add_frien">
                    <h3>Пригласить в друзья<a href="#" class="close" title="Закрыть"></a></h3>

                    <div class="i">
                        <img src="img/tmp/img6_min.jpg" alt="">
                        <span class="name">Алексей</span>
                        <span class="from">Украина, Киев</span>
                        <span class="date">7 июня 2012, 17:26</span>
                    </div>
                    <div class="a">
                        <div class="hi">
                            <div class="tt"></div>
                            <div class="cc">
                                <div class="text">
                                    <div class="ttt"></div>
                                    <div class="tc">
                                        <textarea name="aboutme">Приветствие</textarea>
                                    </div>
                                    <div class="tb"></div>
                                </div>
                                <div class="clr"></div>
                                <input type="submit" class="submit" value="Пригласить">
                            </div>
                            <div class="bb"></div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="b"></div>
    </div>
    <div class="modal" style="display: none;">
        <script type="text/javascript">
            $(document).ready(function () {
                $('.present').stylingform();
            });
        </script>
        <div class="t"></div>
        <div class="clr"></div>
        <div class="c">
            <div class="present">
                <form action="/present/" method="post" name="present">
                    <h3>сделать подарок<a href="#" class="close" title="Закрыть"></a></h3>

                    <div class="l">
                        <div class="item"><a href="#" title=""><img src="img/present/1.jpg" alt=""></a></div>
                        <div class="item"><a href="#" title=""><img src="img/present/2.jpg" alt=""></a></div>
                        <div class="item"><a href="#" title=""><img src="img/present/3.jpg" alt=""></a></div>
                        <div class="item"><a href="#" title=""><img src="img/present/4.jpg" alt=""></a></div>
                        <div class="item"><a href="#" title=""><img src="img/present/5.jpg" alt=""></a></div>
                        <div class="item"><a href="#" title=""><img src="img/present/6.jpg" alt=""></a></div>
                    </div>
                    <div class="sep"></div>
                    <div class="r">
                        <div class="checkbox">
                            <div class="check"><input type="checkbox" name="po"></div>
                            <span>Подмигнуть</span>
                        </div>
                        <div class="checkbox">
                            <div class="check"><input type="checkbox" name="pv" checked="checked"></div>
                            <span>Подарить VIP</span>
                        </div>
                        <div class="checkbox">
                            <div class="check"><input type="checkbox" name="pa"></div>
                            <span>Поднять анкету</span>
                        </div>
                    </div>
                    <div class="clr"></div>
                    <input type="submit" class="submit" value="Подарить">

                </form>

            </div>

        </div>

        <div class="b"></div>

    </div>

{% endblock %}

src/userena/templates/userena/signout.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Signed out" %}{% endblock %}
{% block content_title %}<h2>{% trans "You have been signed out" %}.</h2>{% endblock %}

{% block content %}
<p>{% trans "You have been signed out. Till we meet again." %}</p>
{% endblock %}